language: node_js

node_js:
  - lts/*
  - node

stages:
  - Test
  - name: Release
    if: branch = master AND sender != "Travis CI"
cache:
  directories:
    - "node_modules"
notifications:
  email: false
jobs:
  include:
    - stage: Release
      node_js: lts/*
      install: yarn install
      before_deploy:
        - git config user.email "travis@travis-ci.org"
        - git config user.name "Travis CI"
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn release
        on:
          branch: master
